#! /usr/bin/env python
# encoding: utf-8

bld(
    features='cxx cxxshlib pyext',
    source=bld.path.ant_glob('**/*.cpp'),
    target='petro',
    name='petro-python',
    use=[
        'STEINWURF_VERSION',
        'pybind11_includes',
        'petro'
    ]
)
